function randomEl(list) {
  var i = Math.floor(Math.random() * list.length);
  return list[i];
}

let adjectives = ["ancient", "arbitrary", "amber", "animistic", "artistic", "rainbow", "boring", "brainstorming", "squarish", "spicy", "rustic", "bubbling", "scruffy", "glittery", "black", "concomitant", "rubbery", "comical", "elegant", "pink", "orange", "neon", "boiling", "freezing", "strong", "sour", "savory", "sweet", "examinable", "grumpy", "feckless", "sleepy", "bashful", "beautiful", "glamorous", "sneezy", "dangerous", "mighty", "historic", "holographic", "juicy", "glorious", "sad", "scary", "nightmarish", "dreamy", "floral", "angelic", "colorful", "fuzzy", "translucent", "cheerful", "quurky", "furious", "joyous", "proud", "friendly", "persuasive", "fresh", "calm", "fierce", "luminous", "mannered", "ferocious", "exuberant", "mandatory", "magical", "mysterious", "kind", "aggressive", "obtuse", "envious", "ugly", "enthusiastic", "refreshing", "energetic", "pleasant", "damp", "magnificent", "modern", "giant", "fancy", "retro", "jumbo", "possible", "impossible", "bright", "noisy", "sandy", "spacious", "bumpy", "dusty", "sticky", "greasy", "tangy", "pickled", "minty", "fruity", "quiet", "turbulent", "toroid", "ubiquitous", "uxorious", "verdant", "voluble", "precious", "wheedling", "withering", "zealous", "charming", "luxurious", "expensive", "huge", "silly", "healthy"];
let nouns = ["island", "palace", "castle", "home", "unicorn's land", "bridge", "laser room", "ground", "plains", "ship", "spaceship", "canvas", "wonderland", "land", "hole", "corner", "planet", "potato farm", "universe", "sky", "curtains", "restroom", "toilet", "school", "canyon", "theme park", "park", "spot", "sea", "summerslam", "oasis", "office", "dollhouse", "bushes", "desert", "meadow", "ice cream shop", "forest", "dungeon", "prison", "hall", "circus", "trampoline", "carousel", "carnival", "camp", "hot air balloon", "dimension", "elephant's back", "house", "royale", "scene", "instance", "world", "bedroom", "kitchen", "storeroom", "styling room", "closet", "garden", "attic", "cellar", "basement", "studio", "foyer", "lawn", "front yard", "back yard", "concert hall", "district", "station", "chapel", "terminal", "depo", "ruins", "bar", "club", "sauna", "pool", "base", "haven", "loft", "shack", "playground", "cabin", "cottage", "shelter", "gallery", "maze", "aquarium", "water park", "safari", "zoo", "mansion", "galaxy", "emptiness", "darkness", "dreamland", "rollercoaster", "zoo", "cradle", "secret room", "hell"];

export function generateName() {
  return `${randomEl(adjectives)} ${randomEl(nouns)}`
}